name: Neordinary_iOS
options:
  deploymentTarget:
    iOS: '18.0'
targets:
  Neordinary_iOS:
    bundleId: cmc-umcHackathon.Ne-O-rdinary-iOS
    type: application
    platform: iOS
    sources:
      - path: Neordinary_iOS
    resources:
      - path: Neordinary_iOS/Resources
    dependencies:
      - sdk: MapKit.framework
      - sdk: CoreLocation.framework
      - package: https://github.com/Alamofire/Alamofire
        requirement: upToNextMajor 5.10.2
      - package: https://github.com/Moya/Moya
        requirement: upToNextMajor 15.0.3
      - package: https://github.com/onevcat/Kingfisher
        requirement: upToNextMajor 8.3.2
      - package: https://github.com/kakao/kakao-ios-sdk
        requirement: upToNextMajor 2.24.2
