name: Neordinary_iOS
options:
  deploymentTarget:
    iOS: '18.0'
targets:
  Neordinary_iOS:
    bundleId: cmc-umcHackathon.Ne-O-rdinary-iOS
    type: application
    platform: iOS
    sources:
      - path: Neordinary_iOS
    resources:
      - path: Neordinary_iOS/Resources
    dependencies:
      - sdk: MapKit.framework
      - sdk: CoreLocation.framework
    info:
      path: Neordinary_iOS/Info.plist
